// src/app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'

export const metadata: Metadata = {
  title: 'Placeholder',
  description: 'Generated by create-solana-dapp',
}

const links = [
  { label: 'Home', path: '/' },
  { label: 'Account', path: '/account' },
  { label: 'Mining', path: '/mining' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className="antialiased">
    <AppProviders>
      <AppLayout links={links}>{children}</AppLayout>
    </AppProviders>
    </body>
    </html>
  )
}
