import './globals.css';
import { AppProviders } from '@/components/app-providers';
import { AppLayout } from '@/components/app-layout';
import React from 'react';
export const metadata = {
    title: 'Placeholder',
    description: 'Generated by create-solana-dapp',
};
const links = [
    { label: 'Home', path: '/' },
    { label: 'Account', path: '/account' },
    { label: 'Mining', path: '/mining' }, // ✅ nouveau lien
];
export default function RootLayout({ children }) {
    return (<html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <AppProviders>
          <AppLayout links={links}>{children}</AppLayout>
        </AppProviders>
      </body>
    </html>);
}
BigInt.prototype.toJSON = function () {
    return this.toString();
};
