// src/app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import React from 'react'

export const metadata: Metadata = {
    title: 'Scaffold',
    description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
        {children}
        </body>
        </html>
    )
}
