[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "6qUyfHoKhZ3hbHQ5PqdfgRD15nEiVnJUDeNhmCmjSYAH"
journal = "AY26s6dtYAMa3Fk3HdKuy1PGenESDQpPUwjaT7vYBQhf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
Initialize = "pnpm run Initialize"
