[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "CHTVq7e9xEFqMf261QhruAmBZsuLCBAEr8NDgcYAnqcV"
journal = "6Use3gwxdkzTci1iyuTsc8NUMUW3ue7AkEpMhgnKxf4T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
initialize = "pnpm run initialize"
