[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "FSyJ9EGkBerkZB6C1DSzDkcmjzohhvydb22FfQptbYQH"
journal = "ADm62xpaCbmAVcVFqhFNLALU1ggsoqGf89WDqNaYJGsD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
Initialize = "pnpm run Initialize"
