[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "4jhEaivAmMLvtkXbhShN7ivx5MSxc27JKj3gXLGZnWuC"
journal = "D17vDa92h2Yf4sCKEurxGUVCbs1v4CceqHRVHiF7QJwf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
initialize = "pnpm run initialize"
