[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "CKqr1tXUJxTkkBdkbpWNWEEyDBkrfus5JXKgZJcXJZBf"
journal = "8LLnccgZftBeyp28iMpZ8zLV1mKkGsecDKCYzdwt2iMd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
initialize = "pnpm run initialize"
