[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anaheim = "8RmTVazK1G3ZJ7EqYZC9FYJejFge98Vyz7T4zVdY8okX"
journal = "3EqwhRqpPezsiVTSBcbbTdSJNsJs8ufN2m2EBCqCVmXC"

[programs.devnet]
anaheim = "4tHvPpUkEcF4US6pW5xWJAHnUg7kpeAKNNcGBrw1PTyH"
journal = "3EqwhRqpPezsiVTSBcbbTdSJNsJs8ufN2m2EBCqCVmXC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/RustroverProjects/anarcrypt.sol/anaheim-putsch-govdapp/anchor/target/deploy/anarcrypt.json"

[scripts]
build = "bash -c 'echo test && echo ok done'"
test_jest = "../node_modules/.bin/jest --preset ts-jest"
test_mocha = "mocha -t 1000000 tests/"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
