[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "EMKno4tmR5KgB9L1QqFwfARkjksgdUoFrPDAaCFBCmXa"
journal = "2cdgezCtQvwn6RQ9XasUrctoN71wwkuG7Lc5nQtPw7PV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
Initialize = "pnpm run Initialize"
