[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "9FXKYdyPqSy7GdLX3MVJPUhN5oTcSE4iFrL9hi1s3uvF"
journal = "H7oVMRmp7QqTMcozHhpnpXpxwqTpWCbZhvnxZTF3JzxZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/anaheim", "programs/journal"]

[scripts]
Initialize = "pnpm run Initialize"
