// src/components/app-footer.tsx
import React from 'react';

export function AppFooter() {
    return (
        <footer className="text-center p-2 bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-400 text-xs">
            Generated by{' '}
            <a
                className="link hover:text-neutral-500 dark:hover:text-white"
                href="https://github.com/RastaDjuss/anaheim-putsch-self-governance-solana-dapp.git"
                target="_blank"
                rel="noopener noreferrer"
            >
                Anarcrypt self governance Anaheim Dapp
            </a>
        </footer>
    );
}