// FILE: src/app/mining/page.tsx
'use client';

import React from 'react';
import { useWallet } from '@solana/wallet-adapter-react';
import { ClientWalletMultiButton } from '@/components/wallet/ClientWalletMultiButton';
import MiningClient from '@/components/mining/MiningClient';
import { TransferSolFeature } from '@/components/account/account-data-access';
import { ClientOnly } from '@/components/ClientOnly';

export default function HomePage() {
    const { connected } = useWallet();

    return (
        <div className="space-y-6 text-center max-w-4xl mx-auto py-8">
            <h1 className="text-4xl md:text-5xl font-bold">Anaheim Community Console</h1>
            <p className="text-lg text-muted-foreground">
                Connect your wallet to interact with the on-chain program.
            </p>

            {/* Show the connected button if the wallet is not connected. */}
            {!connected && (
                <div className="flex justify-center py-4">
                    <ClientWalletMultiButton />
                </div>
            )}

            {/*
        ✅ MERGE FIX 3: If the wallet is connected, we render the smart components.
        MiningClient will now handle its own state (loading, not initialized, or initialized).
      */}
            {connected && (
                <ClientOnly>
                    <div className="flex flex-col md:flex-row justify-center items-start gap-8 p-4 border-t">
                        <MiningClient />
                        <TransferSolFeature />
                    </div>
                </ClientOnly>
            )}

            <p className="text-xs text-muted-foreground mt-8">
                Generated by Anarcrypt self governance Anaheim Dapp
            </p>
        </div>
    );
}